language: bash
dist: trusty
sudo: required

before_script:
    - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - lib32gcc1
    - libstdc++6
    - libstdc++6:i386
    - git

script:
  - bash ./steamcmdcommands.sh

after_success:
  - ./push.sh

env:
  global:
    secure: ulaDHkK1udL86HoAXfX7fBu47wcwzmzM4UTIpcr9x+Th8gUMvm/oThJyM1LAqSOIS6WWlmfnKjv0NnU0mIhX2yhgFYaVc4OEd7xNKN1oOYnEFRqtOzzh2iViAW7qMoIHRiN8RperbUKyNbB1BQiajRbsjZA0GUaT7iIG5DXLe7IyqhpoblX1rtqOr8n9SQlz9pTe4ygOcC4AOaw/G/0WLRHw5RgR2su1LYFXekIN4zbu4+lN5LwX4thxl1K+yVOL/OmDIAit/1nZ6FnY4oaIgGosVc0aBXRuzf1eFr42HixcxkVV6vKM0QibguHxLKb9Duss7HD3tBkyYofoDYXTIX3vIfpWkSuGQgY30KMiPkH9DjGs7rUNHWul064IvDJjbU0tIpbZf8p6F2Ajz5ISv7REOjxxYXTfx7SVePdFJ4IoLf6EoyNbqtQdgP5EOpOadxCmi4g4ZDk462hcHZMu2h0Su8S/x6Vcl0mOeVJX7PfxFoxGdXNJZ0z3Pbi3PtVpZwavXcd9SLj/2ix1eVfe7MOTErMyo3m4lu+1IkeDOQcPuo+chE3+4E67SdRWVnr5nCPzbdZGYtFGo+BfabbjLYRkdXN2RpWITMURcvT+vCueYd2kchVFa+2f/eK+4bEgJmPe6Veb8ZPdVt/q9cZuYGvRzgHaxQJGEO8N6bk3XrA=