name: Prettier
on:
  push:
    branches:
      - "*"

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prettify code
        uses: creyD/prettier_action@v4.6
        with:
          prettier_plugins: "prettier-plugin-sh"
          prettier_options: .
